import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import { StoreProvider } from '@/app/StoreProvider'
import { AuthProvider } from '@/lib/feature/auth/ui/AuthProvider'
import { AlertProvider } from '@/components/ui/Alert/AlertProvider'
import { Header } from '@/components/ui/header/Header'
import { Sidebar } from '@/components/ui/sidebar/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <div id='alert-root' />
        <StoreProvider>
          <AuthProvider>
            <AlertProvider>
              <Header />
              <div className='max-w-[1920px]'>
                <div className='flex'>
                  <Sidebar />
                  <main className='ml-[220px] w-full px-6 pt-[60px]'>{children}</main>
                </div>
              </div>
            </AlertProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
