import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import { StoreProvider } from '@/app/StoreProvider'
import { AuthProvider } from '@/lib/feature/auth/ui/AuthProvider'
import { Header } from '@/components/ui/header/Header'
import { AlertProvider } from '@/components/ui/Alert/AlertProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <div id='alert-root' />
        <StoreProvider>
          <AuthProvider>
            <AlertProvider>
              <Header />
              <main className={'pt-[60px]'}>{children}</main>
            </AlertProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
