import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import { StoreProvider } from '@/app/StoreProvider'
import { AuthProvider } from '@/lib/feature/auth/ui/AuthProvider'
import { Header } from '@/components/ui/header/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <StoreProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
